version: '3.7'
 
services:
    manager:
        container_name: manager
        build: ./manager
        ports:
          - '3000:3000'
        environment: 
          MYSQL_HOST: database
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: managerdb
        restart: on-failure
        depends_on: 
          - db
          - redis
        links:
          - db
          - redis

    db:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      container_name: database
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      restart: on-failure
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro
    
    redis:
      build: ./redis
      container_name: redis
      ports:
        - '6379:6379'
    