version: '3.7'
 
services:
    manager:
        container_name: manager
        build: ./manager
        ports:
          - '3000:3000'
        restart: on-failure
        depends_on: 
          - db

    db:
      image: mysql:latest
      container_name: database
      ports:
        - "32000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      restart: on-failure
      volumes:
        - ./model:/docker-entrypoint-initdb.d/:ro
    